"""add participants table

Revision ID: 4c208084908b
Revises: cb0dd356e35b
Create Date: 2026-04-04 23:39:49.297419

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c208084908b'
down_revision: Union[str, Sequence[str], None] = 'cb0dd356e35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('linkedin_acc', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('github_acc', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('x_acc', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('profile_photo_file_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('talent_visible', sa.Boolean(), nullable=False),
    sa.Column('talent_contact_shareable', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_display_name'), 'participants', ['display_name'], unique=True)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_display_name'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
